### ISSUE TITLE
"I'm feeling lucky" search

### ISSUE THREAD

**Issue by domportera** [sophie-glk/bang#25] opened 2022-10-18 18:58 UTC
it would be great to have this DDG feature in the extension.

Basically when searching DDG if you just put a ` ! ` in your search with a space preceding and following it, it will do an "I'm feeling lucky" and bring you directly to the page of its first result

The search query for this in DDG is quite simple

In my region, this is the query i get for searching `something`:
`https://duckduckgo.com/?q=something+%21&t=ha&va=j`

Also thank you for making this amazing extension. was hoping to use ecosia for ethical reasons but couldn't do without DDG bangs and you've made this possible :)

**Comment by babastienne** [comment] 2022-10-24 15:40
Duplicate of #16

**Closed as completed** 2022-10-24 15:42 UTC
